### PR TITLE
Bring new cpu.requests formula from Kubernetes

### LINKED ISSUE #7202: ResourceMonitoring - LinuxUtilizationParserCgroupV2.cs - Formula to calculate cpuUnits based on cpu.weight is outdated.
### Description

I came across this new K8s blog (not published yet) which shows that the formula for converting cpu from cgroupv1 to cgroupv2 is changed: https://github.com/kubernetes/website/blob/40a6197ccb5b356ede5647aa87af13ff1ced4db3/content/en/blog/_posts/2025-10-25-new-cgroup-v1-to-v2-conversion-formula/index.md

New formula: `cpu.weight = ⌈ 10 ^ (L^2 / 612 + 125 * L / 612 − 7 / 34) ⌉, where: L=log2⁡(cpu.shares)` (Please verify this with the code)
Old formula: `cpu.weight = (1 + ((cpu.shares - 2) * 9999) / 262142)`
 
The formula in [LinuxUtilizationParserCgroupV2.cs](https://github.com/dotnet/extensions/blob/main/src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Linux/LinuxUtilizationParserCgroupV2.cs#L832) should be updated according to the new formula so that the `request.utilization` reports correct value. There can be other wrong metrics, which i may not aware, which are relying on the CPU request. 
 
Reference Thread: https://github.com/kubernetes/kubernetes/issues/131216
Reference K8s PRs: 
- https://github.com/opencontainers/cgroups/pull/20
- https://github.com/cri-o/cri-o/pull/9271
- https://github.com/containerd/cgroups/pull/375

### Reproduction Steps

I checked on an AKS cluster v1.32.7 that `cpu.weight` is calculated with the new formula. 

High level steps:  
- Run a container with cpu request `100m`
- Exec into the container 
- `cat /sys/fs/cgroup/cpu.weight`. The value would be `17` based on the new formula.

### Expected behavior

The formula in [LinuxUtilizationParserCgroupV2.cs](https://github.com/dotnet/extensions/blob/main/src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Linux/LinuxUtilizationParserCgroupV2.cs#L832) should be updated according to the new formula so that the `request.utilization` reports correct value. 

### Actual behavior

The formula in [LinuxUtilizationParserCgroupV2.cs](https://github.com/dotnet/extensions/blob/main/src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Linux/LinuxUtilizationParserCgroupV2.cs#L832) is using the old formula and the `request.utilization` is reporting incorrect values. 

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

- Dotnet SDK: 8.0.410
- OS: Linux
- `<PackageReference Include="Microsoft.Extensions.Diagnostics.ResourceMonitoring" Version="10.0.0" />`

### Other information

_No response_

### PR DESCRIPTION
**Pull request by amadeuszl**
Fix #7202
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/extensions/pull/7239)

### Observations
for 1CPU, when it equals to weight 102, it will result in baseline for calculations on around ~1.0253, which means that previously reported utilization at 20% will be reported now as <20%, suggesting that we are getting more CPU

### CODE REVIEW

File: src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Linux/LinuxUtilizationParserCgroupV2.cs [hunk 1]
```diff
@@ -824,16 +824,30 @@ private static bool TryParseCpuWeightFromFile(IFileSystem fileSystem, FileInfo c
...
         }
 
-        // The formula to calculate CPU pod weight (measured in millicores) from CPU share:
-        // y = (1 + ((x - 2) * 9999) / 262142),
-        // where y is the CPU pod weight (e.g. cpuPodWeight) and x is the CPU share of cgroup v1 (e.g. cpuUnits).
-        // https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2254-cgroup-v2#phase-1-convert-from-cgroups-v1-settings-to-v2
-        // We invert the formula to calculate CPU share from CPU pod weight:
-        cpuUnits = ((cpuPodWeight - 1) * 262142 / 9999) + 2;
-
+        cpuUnits = ConvertCpuWeightToShares(cpuPodWeight);
```
Comment (amadeuszl) [inline src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Linux/LinuxUtilizationParserCgroupV2.cs:827]: @evgenyfedorov2 as it's a bug (and was a bug in K8s) and it's a permanent fix for newer Kubernetes I think we don't have to bring any feature flags. WDYT?

Comment (evgenyfedorov2) [reply src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Linux/LinuxUtilizationParserCgroupV2.cs:827]: > I think we don't have to bring any feature flags. WDYT?

Agree.

Also, I don't consider it a bug on our side because our formula was aligned with K8s in the past and nobody could predict the future.

**Review by evgenyfedorov2 — APPROVED** [review]
