### PR TITLE
Make exception summarizer work with derived exception types

### LINKED ISSUE #4004: Exception summarization should understand subclasses
Right now, the exception summarization logic only summarizes exact exception types. To match the semantics of exceptions, it really should be matching against types and derived types.

### PR DESCRIPTION
**Pull request by geeknoid**
Fixes #4004 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/extensions/pull/4370)

### CODE REVIEW

**Review by rafal-mz — APPROVED** [review]

File: src/Libraries/Microsoft.Extensions.Diagnostics.ExceptionSummarization/Implementation/ExceptionSummarizer.cs [hunk 1]
```diff
@@ -35,21 +28,22 @@ public ExceptionSummarizer(IEnumerable<IExceptionSummaryProvider> providers)
         _exceptionTypesToProviders = exceptionTypesToProvidersBuilder.ToFrozenDictionary();
     }
 
-    /// <summary>
-    /// It iterates through all registered summarizers, returns a summary if possible.
-    /// Default is <see cref="Exception"/> message if its length is less than 32, otherwise exception type name.
-    /// </summary>
-    /// <param name="exception">The exception.</param>
-    /// <returns>The summary of the given <see cref="Exception"/>.</returns>
```
Comment (RussKie) [inline src/Libraries/Microsoft.Extensions.Diagnostics.ExceptionSummarization/Implementation/ExceptionSummarizer.cs:43]: Why delete the existing xml-docs? They can still be useful.
