### PR TITLE
ResourceUtilizationHealthCheck - Report both CPU and Memory issues

### LINKED ISSUE #4677: ResourceUtilizationHealthCheck only reports CPU _or_ memory issues, not both
### Description

When checking health based on resource utilization, the conditions are checked in series and only the first failure is reported.
https://github.com/dotnet/extensions/blob/68810ca7399be38b8490a114ef52fdae4ce00058/src/Libraries/Microsoft.Extensions.Diagnostics.HealthChecks.ResourceUtilization/ResourceUtilizationHealthCheck.cs#L39-L60

### Reproduction Steps

Test on a system with both high CPU _and_ memory.

### Expected behavior

Both CPU and memory issues should be reported.

### Actual behavior

Only the first issue found is reported.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

8.0

### Other information

Recommendation: ResourceUtilizationHealthCheck should be split into two IHealthCheck implementations, one for CPU and one for memory. That way both states can be reported independently.

### PR DESCRIPTION
**Pull request by willibrandon**
Fixes #4677 

## Proposed changes

- Report both CPU and Memory issues when checking health based on resource utilization.

## Customer Impact

- Fixes an issue where only CPU or Memory issues are reported during a resource utilization health check, but not both.
- This change also includes the additional key-value pairs describing the health of each component in the health check result.

## Test methodology 

- Updated `ResourceHealthCheckTests` to accommodate for this change.
- Ran all tests.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/extensions/pull/5407)

### CODE REVIEW

File: src/Libraries/Microsoft.Extensions.Diagnostics.HealthChecks.ResourceUtilization/ResourceUtilizationHealthCheck.cs [hunk 1]
```diff
@@ -39,26 +39,58 @@ public ResourceUtilizationHealthCheck(IOptions<ResourceUtilizationHealthCheckOpt
...
+            else if (cpuUnhealthy)
+            {
+                message = "CPU";
+            }
+            else
+            {
+                message = "Memory";
+            }
+
+            message += " usage is above the limit";
```
Comment (RussKie) [inline src/Libraries/Microsoft.Extensions.Diagnostics.HealthChecks.ResourceUtilization/ResourceUtilizationHealthCheck.cs:67]: I suggest creating dedicated strings for each case to avoid extra allocations.

File: src/Libraries/Microsoft.Extensions.Diagnostics.HealthChecks.ResourceUtilization/ResourceUtilizationHealthCheck.cs [hunk 2]
```diff
@@ -39,26 +39,58 @@ public ResourceUtilizationHealthCheck(IOptions<ResourceUtilizationHealthCheckOpt
...
+        bool memoryUnhealthy = utilization.MemoryUsedPercentage > _options.MemoryThresholds.UnhealthyUtilizationPercentage;
 
-        if (utilization.CpuUsedPercentage > _options.CpuThresholds.DegradedUtilizationPercentage)
+        if (cpuUnhealthy || memoryUnhealthy)
         {
-            return Task.FromResult(HealthCheckResult.Degraded("CPU usage is close to the limit"));
+            string message = string.Empty;
+            if (cpuUnhealthy && memoryUnhealthy)
+            {
+                message = "CPU and Memory";
```
Comment (RussKie) [inline src/Libraries/Microsoft.Extensions.Diagnostics.HealthChecks.ResourceUtilization/ResourceUtilizationHealthCheck.cs:56]:
```suggestion
                message = "CPU and memory";
```

Ditto below

**Comment by willibrandon** [comment]
@RussKie thanks for the feedback; commit with suggestions pushed.

**Review by RussKie — APPROVED** [review]

**Comment by RussKie** [comment]
@evgenyfedorov2 @sebastienros

**Review by evgenyfedorov2 — APPROVED** [review]

**Comment by RussKie** [comment]
Thank you
