### PR TITLE
Guard for Custom Implementation of IHostApplicationLifetime 

### LINKED ISSUE #2825: NullReferenceException with custom implementation of IHostApplicationLifetime
### Describe the bug
A custom implementation of `IHostApplicationLifetime` causes a `NullReferenceException`.

### To Reproduce
```csharp
public class Program
{
    public static void Main(string[] args)
    {
        CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureServices((hostContext, services) =>
            {
                services.AddSingleton<IHostApplicationLifetime, CustomApplicationLifetime>();
                services.AddHostedService<Worker>();

            });
}

public class CustomApplicationLifetime : IHostApplicationLifetime
{
    public CancellationToken ApplicationStarted => default;

    public CancellationToken ApplicationStopping => default;

    public CancellationToken ApplicationStopped => default;

    public void StopApplication()
    {
    }
}
```

### Additional context
This is where error is happening.
https://github.com/aspnet/Extensions/blob/ecc4d9fe9381ac65848968b672eb6098ec2a2cae/src/Hosting/Hosting/src/Internal/Host.cs#L39

There's no null checking for `_applicationLifetime`. In order to fix this we could store `IHostApplicationLifetime` instead of `ApplicationLifetime` and use cast in `StartAsync(...)` and `StopAsync(...)`

### PR DESCRIPTION
**Pull request by Kahbazi**
- Added a gaurd for IHostApplicationLifetime
- Removed null checks

Fixes #2825

### CODE REVIEW

File: src/Hosting/Hosting/src/Internal/Host.cs [hunk 1]
```diff
@@ -25,6 +25,10 @@ internal class Host : IHost, IAsyncDisposable
         {
             Services = services ?? throw new ArgumentNullException(nameof(services));
             _applicationLifetime = (applicationLifetime ?? throw new ArgumentNullException(nameof(applicationLifetime))) as ApplicationLifetime;
+            if (_applicationLifetime is null)
```
Comment (Tratcher) [inline src/Hosting/Hosting/src/Internal/Host.cs]: `is null` vs `== null`?

File: src/Hosting/Hosting/src/Internal/Host.cs [hunk 2]
```diff
@@ -25,6 +25,10 @@ internal class Host : IHost, IAsyncDisposable
...
+            {
+                throw new ArgumentException("The only acceptable implementation of Microsoft.Extensions.Hosting.IHostApplicationLifetime is Microsoft.Extensions.Hosting.Internal.ApplicationLifetime", nameof(applicationLifetime));
```
Comment (Tratcher) [inline src/Hosting/Hosting/src/Internal/Host.cs]:
```suggestion
                throw new ArgumentException("Replacing IHostApplicationLifetime is not supported.", nameof(applicationLifetime));
```

**Comment by Tratcher** [comment]
Thanks
