### PR TITLE
Separate EnableRedaction and EnableEnrichment

### LINKED ISSUE #4683: Inconsistent behavior in extended logging
### Description

Current implementation of ExtendedLogger enables both enrichment and redaction regardless of what was enabled.

### Reproduction Steps

**Scenario №1:**
```cs
using var loggerFactory =
    LoggerFactory.Create(builder =>
    {
        builder.EnableRedaction();
        builder.Services.AddLogEnricher<CustomEnricher>();
    });

var logger = loggerFactory.CreateLogger("MyDemoLogger");
```

Even though I haven't enabled enrichment, the `CustomEnricher` will be called.

**Scenario №2:**
```cs
using var loggerFactory =
    LoggerFactory.Create(builder =>
    {
        builder.EnableEnrichment();
        builder.Services.AddRedaction();
    });

var logger = loggerFactory.CreateLogger("MyDemoLogger");
```

Even though I haven't enabled redaction, the `ErasingRedactor` will be called to redact data annotated with data classification.

**Scenario №3:**
One more confusing thing is that when I enable redaction feature, but don't have any redactors registered, I would get sensitive data being emitted as-is. Consider this example:
```cs
using var loggerFactory = LoggerFactory.Create(builder => builder.EnableRedaction());
var logger = loggerFactory.CreateLogger("MyDemoLogger");
Log.LogMethod(logger, "Sensitive user name");

internal static partial class Log
{
    [LoggerMessage(Level = LogLevel.Warning, Message = "User {Name} has now different status")]
    public static partial void LogMethod(ILogger logger, [PrivateData] string name);
}
```

### Expected behavior

Each call to `EnableRedaction()` and `EnableEnrichment()` enables the corresponding feature only.

### Actual behavior

Any of calls `EnableRedaction()` and `EnableEnrichment()` apply both of them.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by geeknoid**
- Prior, calling EnableRedaction or EnableEnrichment would always enable both enrichment and redaction together. Now, each call only affects the specific feature it is intended.

Fixes #4683

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/extensions/pull/4838)

### CODE REVIEW

File: src/Libraries/Microsoft.Extensions.Telemetry/Logging/ExtendedLoggerFactory.cs [hunk 1]
```diff
@@ -63,6 +63,16 @@ internal sealed class ExtendedLoggerFactory : ILoggerFactory
         _filterOptionsChangeTokenRegistration = filterOptions.OnChange(RefreshFilters);
         RefreshFilters(filterOptions.CurrentValue);
 
+        if (enrichmentOptions == null)
```
Comment (RussKie) [inline src/Libraries/Microsoft.Extensions.Telemetry/Logging/ExtendedLoggerFactory.cs:66]: [nit]
```suggestion
        if (enrichmentOptions is null)
```

**Review by RussKie — APPROVED** [review]

**Review by xakep139 — APPROVED** [review]
